### PR TITLE
Add Ukraine country

### PR DESCRIPTION
**Pull request by chbgdn**
JustWatch added Ukraine as supported country, so let's add it to Showly too.

P.S. Right now JustWatch search link using Ukraine country code return 404 error (only if using direct link, when using search on site all works well). I sent feedback to them, so need to wait reply and fixing this bug before merging this PR.

### CODE REVIEW

**Comment by michaldrabik** [comment]
Feel free to mark it ready for review whenever JustWatch makes their update.

**Comment by chbgdn** [comment]
@michaldrabik I received reply from JustWatch Support more than 3 weeks ago, but bug is not fixed yet. Hope it will be fixed soon.
PR is ready for review now :)

**Comment by michaldrabik** [comment]
Yeah PR is good - just don't want to add this unless its working on JustWatch side too.

**Comment by chbgdn** [comment]
Sure, I will let you know when JustWatch fixed issue on their side.

**Pull request closed without merging**
